version: "3"
services:
  coursematerial:
    #image: devopsdockeruh/coursepage
    image: maebius/devopsdockeruh-coursepage
    ports:
      - 4000:80
    container_name: coursematerial
  watchtower: # this to listen changes in containers #2
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower